#!/bin/bash

source bin/funcs.sh
banner
if [[ -e 'split' || -e 'ramdisk' ]]
then
    echo -n '[+]Clean workspace'
    rm -rf split ramdisk
    echo -e '\t\tDone'
else
    echo '[!]Nothing to clean'
fi

