#!/bin/bash

source bin/funcs.sh
if [[ -e 'split' || -e 'ramdisk' ]]
then
    printf '%-40s' '[+]Clean workspace'
    rm -rf split ramdisk
    printf 'Done\n'
else
    printf '[!]Nothing to clean\n'
fi

