#!/bin/bash

source bin/funcs.sh
chkarch
banner
RPWD=`pwd`
IMG="$RPWD/split/source.img"

if [[ -d $RPWD/ramdisk ]]
then
    cd $RPWD/ramdisk
    find . | cpio -H newc -o > $RPWD/split/ramdisk.cpio
fi

if [[ -f "$IMG" ]]
then
    cd $RPWD/split
    $MAGISKBOOT repack $IMG
    mv new-boot.img ..
else
    usage
    exit 1
fi

