#!/bin/bash

source bin/funcs.sh
banner
RPWD=`pwd`
[ ! -d "$RPWD/split" ] && echo '[!]Unpack an image first' && exit

RDTYPE=`cat "$RPWD/split/ramdisk_compression"`
[ "$RDTYPE" == 'zst' ] && RDTYPE='zstd'

if [[ -d $RPWD/ramdisk ]]
then
    echo -n '[+]Compressing ramdisk'
    cd $RPWD/ramdisk
    TMP=$RPWD/split/ramdiskcpio.tmp
    RAMDISK=$RPWD/split/ramdisk
    find . | cpio --quiet -H newc -o > $TMP
    if [[ "$RDTYPE" == 'Unknown' || "$RDTYPE" == 'cpio' ]]; then
        mv $TMP $RAMDISK
    else
        $RDTYPE -c $TMP > $RAMDISK
        rm $TMP
    fi
    echo -e '\t\tDone'
fi

if [[ -f "$RPWD/split/mkcmd" ]]
then
    echo -n '[+]Creating new image'
    sh $RPWD/split/mkcmd && \
        echo -e '\t\tDone'
else
    usage
    exit 1
fi

