#!/bin/bash

source bin/funcs.sh
chkarch
banner
RPWD=`pwd`

if [ "$1" == "help" ]
then
    usage
    exit 0
elif [ -f "$1" ]
then
    ./cleanup
    IMG=`realpath $1`
else
    echo -e '[!]Input Error\n'
    usage
    exit 1
fi

mkdir -p $RPWD/split $RPWD/ramdisk
cat $IMG > $RPWD/split/source.img
cd $RPWD/split
$MAGISKBOOT unpack -h $IMG
cd $RPWD/ramdisk
cpio -i < $RPWD/split/ramdisk.cpio

